`•`,
  `Resident Evil Village F.C. est. 1894`,
  `Aug 27, 2021`,
  `https://www.youtube.com/watch?v=8x8kNFjpwsE`,
  `https://archive.org/details/Voyerism00`,
  `•`,
  `FAT 32 QUICKBLAST`,
  `Aug 29, 2021`,
  `https://www.youtube.com/watch?v=erRqLICGTV8`,
  `https://archive.org/details/nc102_ufos`,
  `•`,
  `FAT 32 QUICK BLAST LISP MICROPHONE FILTER EXTREME EDITION`,
  `Oct 12, 2022 `,
  `https://www.youtube.com/watch?v=f_0mBHx6afc`,
  `https://archive.org/details/CyberCha98`,
  `•`,
  `FAT 32 QUICK BLAST`,
  `Oct 20, 2022`,
  `https://www.youtube.com/watch?v=CpZC91gwpUw`,
  `https://archive.org/details/nc101_hackers`,
  `•`,
  `Silent Hill 2 - Part 4`,
  `Dec 12, 2022`,
  `https://www.youtube.com/watch?v=axkKe_lfVdQ`,
  `https://archive.org/details/nc103_dating_romance`,
  `•`,
  `Silent Hill 2 - Part 4`,
  `Dec 12, 2022`,
  `https://www.youtube.com/watch?v=axkKe_lfVdQ`,
  `https://archive.org/details/CyberDat`,
  `•`,
  `FAT 32 QUICK BLAST - CHEIFEIT-M (A.M.)`,
  `Dec 20, 2022`,
  `https://www.youtube.com/watch?v=p1dc-7pkXlk`,
  `https://archive.org/details/StateOfT02`,
  `•`,
  `FAT 32 QUICK BLAST - CHEIFEIT-M (A.M.)`,
  `Dec 20, 2022`,
  `https://www.youtube.com/watch?v=p1dc-7pkXlk`,
  `https://archive.org/details/nc102_comics`,
  `•`,
  `StreamZONE`,
  `Jan 22, 2024`,
  `https://www.youtube.com/watch?v=qRwHNaFhsEI`,
  `https://archive.org/details/nc104_dark_side_of_the_net`,
  `•`,
  `StreamZONE`,
  `Jan 22, 2024`,
  `https://www.youtube.com/watch?v=qRwHNaFhsEI`,
  `https://archive.org/details/JustforF1999`,
  `•`,
  `Roachzone Part 2`,
  `Feb 2, 2024`,
  `https://www.youtube.com/watch?v=NbXF06F-e9E`,
  `https://archive.org/details/CyberSpo99`,
  `•`,
  `Roachzone Part 2`,
  `Feb 2, 2024`,
  `https://www.youtube.com/watch?v=NbXF06F-e9E`,
  `https://archive.org/details/nc147_virtual_zoo`,
  `•`,
  `StreamZONE`,
  `Mar 6, 2024`,
  `https://www.youtube.com/watch?v=M-o_ppS1pNI`,
  `https://archive.org/details/nc119_disinformation`,
  `•`,
  `FACE of WAR: Chaos Theory`,
  `Mar 15, 2024`,
  `https://www.youtube.com/watch?v=TnZWb6DMPoE`,
  `https://archive.org/details/GrimReap98`,
  `•`,
  `FACE of WAR: Chaos Theory`,
  `Mar 15, 2024`,
  `https://www.youtube.com/watch?v=TnZWb6DMPoE`,
  `https://archive.org/details/NetGames00`,
  `•`,
  `Resident Stephen 3 (pt. 2)`,
  `Mar 25, 2024`,
  `https://www.youtube.com/watch?v=1ej4D13UyqM`,
  `https://archive.org/details/nc351_xtreme_web`,
  `•`,
  `Resident Stephen 3 (pt. 2)`,
  `Mar 25, 2024`,
  `https://www.youtube.com/watch?v=1ej4D13UyqM`,
  `https://archive.org/details/CyberCom99`,
  `•`,
  `New Vegas (Pt.3) quickblast`,
  `Apr 7, 2024`,
  `https://www.youtube.com/watch?v=tJ7ES9NJDIU`,
  `https://archive.org/details/nc117_weird_web`,
  `•`,
  `Stream`,
  `April 23, 2024`,
  `https://www.youtube.com/watch?v=gzZchH67HQo`,
  `https://archive.org/details/Conspira2001`,
  `•`,
  `More Disturbance`,
  `Nov 7, 2024`,
  `https://www.youtube.com/watch?v=MugtdW2NP-E`,
  `https://archive.org/details/nc103_cyberpolitics`,
  `•`,
  `Cruel Situations`,
  `Dec 4, 2024`,
  `https://www.youtube.com/watch?v=VGyDS8ag0zM`,
  `https://archive.org/details/Buyitonl98`,
  `•`,
  `Unending Cruelty 2025`,
  `Jan 5, 2025`,
  `https://www.youtube.com/watch?v=phrYsVgQRs0`,
  `https://archive.org/details/nc104_art`,
  `•`,
  `THE END OF SILENT HILL 3`,
  `Jan 6, 2025`,
  `https://www.youtube.com/watch?v=W2WJNgdAGHM`,
  `https://archive.org/details/nc217_online_activism`;
