const data = [
  { gdelt: `Adventure Travel Online`, tvdb: `Adventure Travel Online` },
  { gdelt: `Art on the Net`, tvdb: `Art on the Net` },
  { gdelt: `Buy It Online`, tvdb: `Buy It Online` },
  { gdelt: `Censorship Online`, tvdb: `Censorship Online` },
  { gdelt: `Chat Rooms`, tvdb: `Chat Rooms` },
  { gdelt: `Comic Books on the Web`, tvdb: `Comic Books on the Web` },
  { gdelt: `Conspiracy Theories (1999)`, tvdb: `Conspiracy Theories (1999)` },
  { gdelt: `Conspiracy Theories (2001)`, tvdb: `Conspiracy Theories (2001)` },
  { gdelt: `Consumer Protection Online`, tvdb: `Consumer Protection Online` },
  { gdelt: `Cool Home Pages`, tvdb: `Cool Home Pages` },
  { gdelt: `Crime and Justice`, tvdb: `Crime and Justice` },
  { gdelt: `Cyber Chat`, tvdb: `Cyber Chat` },
  { gdelt: `Cyber Communities`, tvdb: `Cyber Communities` },
  { gdelt: `Cyber News`, tvdb: `Cyber News` },
  { gdelt: `Cyber Sports`, tvdb: `Cyber Sports` },
  { gdelt: `Cyber Writing`, tvdb: `Writers` },
  { gdelt: `Cyber Kids`, tvdb: `Cyber Kids` },
  { gdelt: `Disinformation on the Web`, tvdb: `Disinformation on the Web` },
  { gdelt: `E-Commerce`, tvdb: `E-Commerce` },
  { gdelt: `Entertainment on the Web`, tvdb: `Entertainment on the Web` },
  { gdelt: `Equality & Diversity On Line`, tvdb: `Equality and Diversity` },
  { gdelt: `Extreme Web`, tvdb: `Xtreme Web` },
  {
    gdelt: `Finding Anyone / Anything Online`,
    tvdb: `Finding Anyone / Anything Online`,
  },
  { gdelt: `Finding People Online`, tvdb: `Finding People Online` },
  { gdelt: `Fun Web Sites`, tvdb: `Just for Fun` },
  {
    gdelt: `Gambling and Gaming on the Web`,
    tvdb: `Gambling and Gaming on the Web`,
  },
  { gdelt: `Games on the Net`, tvdb: `Games on the Net` },
  {
    gdelt: `Grim Reaper Web Sites (1998)`,
    tvdb: `Grim Reaper Web Sites (1998)`,
  },
  {
    gdelt: `Grim Reaper Web Sites (2000)`,
    tvdb: `Grim Reaper Web Sites (2000)`,
  },
  {
    gdelt: `Group Therapy Net Style (1998)`,
    tvdb: `Group Therapy Net Style (1998)`,
  },
  {
    gdelt: `Group Therapy Net Style (2002)`,
    tvdb: `Group Therapy Net Style (2002)`,
  },
  { gdelt: `Hackers`, tvdb: `Hackers` },
  { gdelt: `Health Sites`, tvdb: `Health Sites` },
  { gdelt: `Hollywood on the Net`, tvdb: `Hollywood on the Net` },
  { gdelt: `Home Improvement`, tvdb: `Home Improvement` },
  { gdelt: `Home Improvement`, tvdb: `Home Improvement` },
  { gdelt: `Humor on the Web`, tvdb: `Humor on the Web` },
  { gdelt: `Humor Online`, tvdb: `Humor Online` },
  { gdelt: `Incredibly Useful Sites`, tvdb: `Incredibly Useful Sites` },
  { gdelt: `Investing Online`, tvdb: `Investing Online` },
  { gdelt: `Jobs and Careers`, tvdb: `Jobs and Careers` },
  { gdelt: `Lifelong Learning`, tvdb: `Lifelong Learning` },
  { gdelt: `Lions and Tigers and Bears`, tvdb: `Lions and Tigers and Bears` },
  { gdelt: `Love and Romance on the Web`, tvdb: `Love and Romance on the Web` },
  { gdelt: `Making Money On Line`, tvdb: `Making Money On Line` },
  { gdelt: `Movies Online`, tvdb: `Movies` },
  { gdelt: `Music Web Sites`, tvdb: `Music` },
  {
    gdelt: `Net Cafe: Web StartUps – April 13, 2000`,
    tvdb: `Web Startups April 13th (2000)`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – April 13, 2001`,
    tvdb: `Web Startups April 13th (2001)`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – April 14, 2000`,
    tvdb: `Web Startups April 14th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – April 20, 2001`,
    tvdb: `Web Startups April 20th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – April 6, 2001`,
    tvdb: `Web Startups April 6th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – April 6, 2001`,
    tvdb: `Web Startups April 6th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Dec 1, 2000`,
    tvdb: `Web Startups December 1st`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Dec 14, 2001`,
    tvdb: `Web Startups December 14th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Dec 7, 2000`,
    tvdb: `Web Startups December 7th (2000)`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Dec 7, 2001`,
    tvdb: `Web Startups December 7th (2001)`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Feb 15, 2002`,
    tvdb: `Web Startups February 15th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Feb 22, 2002`,
    tvdb: `Web Startups February 22nd`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Jan 11, 2002`,
    tvdb: `Web Startups January 11th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Jan 4, 2002`,
    tvdb: `Web Startups January 4th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – June 1, 2001`,
    tvdb: `Web Startups June 1st`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – June 1, 2001`,
    tvdb: `Web Startups June 1st`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – June 15, 2001`,
    tvdb: `Web Startups June 15th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – June 15, 2001`,
    tvdb: `Web Startups June 15th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – June 29, 2001`,
    tvdb: `Web Startups June 29th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – June 8, 2001`,
    tvdb: `Web Startups June 8th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – June 8, 2001`,
    tvdb: `Web Startups June 8th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – March 9, 2001`,
    tvdb: `Web Startups March 9th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – May 11, 2001`,
    tvdb: `Web Startups May 11th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – May 11, 2001`,
    tvdb: `Web Startups May 11th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – May 26, 2000`,
    tvdb: `Web Startups May 26th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – May 4, 2001`,
    tvdb: `Web Startups May 4th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – May 4, 2001`,
    tvdb: `Web Startups May 4th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – May 4, 2001`,
    tvdb: `Web Startups May 4th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – May 5, 2000`,
    tvdb: `Web Startups May 5th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – November 3, 2000`,
    tvdb: `Web Startups November 3rd`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Oct 13, 2000`,
    tvdb: `Web Startups October 13th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Oct 20, 2000`,
    tvdb: `Web Startups October 20th`,
  },
  {
    gdelt: `Net Cafe: Web StartUps – Oct 6, 2000`,
    tvdb: `Web Startups October 6th`,
  },
  { gdelt: `Net Games`, tvdb: `Net Games` },
  { gdelt: `New Age Web Sites`, tvdb: `New Age Websites` },
  { gdelt: `New Web Sites – Part 1`, tvdb: `New Web Sites` },
  { gdelt: `Interesting Web Sites`, tvdb: `Interesting Web Sites` },
  {
    gdelt: `Nicholas Negroponte – Part One`,
    tvdb: `Nicholas Negroponte Part One`,
  },
  {
    gdelt: `Nicholas Negroponte – Part Two`,
    tvdb: `Nicholas Negroponte Part Two`,
  },
  { gdelt: `Online Activism`, tvdb: `Online Activism` },
  { gdelt: `Online Collecting`, tvdb: `Online Collecting` },
  { gdelt: `Online Job Hunting`, tvdb: `Online Job Hunting` },
  { gdelt: `Online Literature`, tvdb: `Online Literature` },
  { gdelt: `Online Sports`, tvdb: `Online Sports` },
  { gdelt: `Performing Arts on the Web`, tvdb: `Performing Arts on the Web` },
  { gdelt: `Performing Arts on the Web`, tvdb: `Performing Arts on the Web` },
  { gdelt: `Politics on the Web`, tvdb: `Politics on the Web` },
  { gdelt: `Portals`, tvdb: `Portals` },
  { gdelt: `Privacy in Cyberspace`, tvdb: `Privacy in Cyberspace` },
  { gdelt: `Safe Kids Safe Net`, tvdb: `Safe Kids Safe Net` },
  { gdelt: `Science Fiction Online`, tvdb: `Science Fiction Online` },
  { gdelt: `Sex Online`, tvdb: `Sex Online` },
  {
    gdelt: `Small Business Resources On the Net`,
    tvdb: `Small Business Resources on the Net`,
  },
  { gdelt: `Space Science`, tvdb: `Space Science` },
  { gdelt: `State of the Web Part Two`, tvdb: `State of the Web` },
  { gdelt: `State of the Web Part Two`, tvdb: `State of the Web` },
  { gdelt: `The 3D Web`, tvdb: `The 3D Web` },
  { gdelt: `The Dark Side of the Web`, tvdb: `Dark Side of the Net` },
  { gdelt: `The Global Net`, tvdb: `The Global Net` },
  { gdelt: `The Hollywood Connection`, tvdb: `The Hollywood Connection` },
  { gdelt: `The Virtual Zoo`, tvdb: `The Virtual Zoo` },
  { gdelt: `The Weird Web`, tvdb: `Weird Web` },
  { gdelt: `Travel Sites Online`, tvdb: `Travel Sites Online` },
  { gdelt: `TV Shows Online`, tvdb: `TV Shows Online` },
  { gdelt: `UFOs`, tvdb: `UFO's` },
  { gdelt: `Virtual Doctors`, tvdb: `Virtual Doctors` },
  { gdelt: `Voyeurism Online:`, tvdb: `Voyeurism Online` },
  { gdelt: `War On The Web`, tvdb: `War on the Web` },
  { gdelt: `Web Radio`, tvdb: `Web Radio` },
  { gdelt: `Webby Awards 1997`, tvdb: `Webby Awards 1997` },
  {
    gdelt: `Webby Awards 1999 – Part One`,
    tvdb: `Webby Awards 1999 - Part One`,
  },
  {
    gdelt: `Webby Awards 1999 – Part Two`,
    tvdb: `Webby Awards 1999 - Part Two`,
  },
  { gdelt: `Webby Awards 2000 – Part One`, tvdb: `Webby Awards 2000 Part One` },
  { gdelt: `Webby Awards 2000 – Part Two`, tvdb: `Webby Awards 2000 Part Two` },
  { gdelt: `Weird Science on the Web`, tvdb: `Weird Science` },
  { gdelt: `Women on the Web`, tvdb: `Women on the Web` },
];
