
  {
    index: 93,
    season: '2000',
    episodeOfSeason: 9,
    titles: ['Grim Reaper Web Sites (2000) '],
    date: 964134000000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 94,
    season: '2000',
    episodeOfSeason: 10,
    titles: ['Web Startups November 3rd'],
    date: 973209600000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 95,
    season: '2000',
    episodeOfSeason: 11,
    titles: ['Web Startups December 7th (2000)'],
    date: 976147200000,
    youtubeURL: 'null',
    internetArchiveURL: ['https://archive.org/details/StateOfT02'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_StateOfT02',
    ],
    watched: true,
    streamTitle: 'FAT 32 QUICK BLAST - CHEIFEIT-M (A.M.)',
    streamDate: 1671494400000,
    streamURL: 'https://www.youtube.com/watch?v=p1dc-7pkXlk',
  },
  {
    index: 96,
    season: '2000',
    episodeOfSeason: 12,
    titles: ['Webby Awards 2000 Part One'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 97,
    season: '2000',
    episodeOfSeason: 13,
    titles: ['Webby Awards 2000 Part Two'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 98,
    season: '2001',
    episodeOfSeason: 1,
    titles: ['Conspiracy Theories (2001)'],
    date: 980985600000,
    youtubeURL:
      'https://www.youtube.com/watch?v=CGjDPGWagc8&pp=ygUjbmV0IGNhZmUgQ29uc3BpcmFjeSBUaGVvcmllcyAoMjAwMSk%3D',
    internetArchiveURL: ['https://archive.org/details/Conspira2001'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Conspira2001',
    ],
    watched: true,
    streamTitle: 'Stream',
    streamDate: 1713826800000,
    streamURL: 'https://www.youtube.com/watch?v=gzZchH67HQo',
  },
  {
    index: 99,
    season: '2001',
    episodeOfSeason: 1,
    titles: ['Interesting Web Sites'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 100,
    season: '2001',
    episodeOfSeason: 2,
    titles: ['New Web Sites'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 101,
    season: '2001',
    episodeOfSeason: 3,
    titles: ['State of the Web'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 102,
    season: '2001',
    episodeOfSeason: 4,
    titles: ['Web Startups March 9th'],
    date: 984096000000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 103,
    season: '2001',
    episodeOfSeason: 5,
    titles: ['Web Startups April 6th'],
    date: 986511600000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 104,
    season: '2001',
    episodeOfSeason: 6,
    titles: ['Web Startups April 13th (2001)'],
    date: 987116400000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 105,
    season: '2001',
    episodeOfSeason: 7,
    titles: ['Web Startups April 20th'],
    date: 987721200000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 106,
    season: '2001',
    episodeOfSeason: 8,
    titles: ['Web Startups May 4th'],
    date: 988930800000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 107,
    season: '2001',
    episodeOfSeason: 9,
    titles: ['Web Startups May 11th'],
    date: 989535600000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 108,
    season: '2001',
    episodeOfSeason: 10,
    titles: ['Web Startups June 1st'],
    date: 991350000000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 109,
    season: '2001',
    episodeOfSeason: 11,
    titles: ['Web Startups June 8th'],
    date: 991954800000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 110,
    season: '2001',
    episodeOfSeason: 12,
    titles: ['Web Startups June 15th'],
    date: 992559600000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 111,
    season: '2001',
    episodeOfSeason: 13,
    titles: ['Web Startups June 29th'],
    date: 993769200000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 112,
    season: '2001',
    episodeOfSeason: 14,
    titles: ['Web Startups October 8th'],
    date: 1002495600000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 113,
    season: '2001',
    episodeOfSeason: 15,
    titles: ['Web Startups December 1st'],
    date: 1007164800000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 114,
    season: '2001',
    episodeOfSeason: 16,
    titles: ['Web Startups December 7th (2001)'],
    date: 1007683200000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 115,
    season: '2001',
    episodeOfSeason: 17,
    titles: ['Web Startups December 14th'],
    date: 1008288000000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 116,
    season: '2002',
    episodeOfSeason: 1,
    titles: ['Home Improvement'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 117,
    season: '2002',
    episodeOfSeason: 2,
    titles: ['Nicholas Negroponte Part One'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 118,
    season: '2002',
    episodeOfSeason: 3,
    titles: ['Nicholas Negroponte Part Two'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 119,
    season: '2002',
    episodeOfSeason: 4,
    titles: ['State of the Web'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 120,
    season: '2002',
    episodeOfSeason: 5,
    titles: ['Web Startups January 4th'],
    date: 1010102400000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 121,
    season: '2002',
    episodeOfSeason: 6,
    titles: ['Web Startups January 11th'],
    date: 1010707200000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 122,
    season: '2002',
    episodeOfSeason: 7,
    titles: ['Web Startups February 15th'],
    date: 1014336000000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 123,
    season: '2002',
    episodeOfSeason: 8,
    titles: ['Web Startups February 22nd'],
    date: 1014336000000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 124,
    season: '2002',
    episodeOfSeason: 9,
    titles: ['Group Therapy Net Style (2002)'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },

