const ytresultsNetcafe = [
  {
    index: 5,
    ourTitle: 'Women on the Web',
    ytTitle: 'Net Cafe: Women On The Web (1996)',
    url: 'https://www.youtube.com/watch?v=4Ii94pqIbDA',
  },
  {
    index: 6,
    ourTitle: 'Games',
    ytTitle: 'Net Cafe - 19961104 - NC106 - Games',
    url: 'https://www.youtube.com/watch?v=yPbmMczw1K0',
  },
  {
    index: 7,
    ourTitle: 'The 3D Web',
    ytTitle: 'Net Cafe: The 3D Web (1996)',
    url: 'https://www.youtube.com/watch?v=Z5WubOHkgew',
  },
  {
    index: 8,
    ourTitle: 'Music',
    ytTitle: 'Net Cafe - 19961118 - NC108 - Music',
    url: 'https://www.youtube.com/watch?v=S86sJx16Xso',
  },
  {
    index: 9,
    ourTitle: 'Movies',
    ytTitle: 'Net Cafe - Movies Online (1996)',
    url: 'https://www.youtube.com/watch?v=NL299SC8zO8',
  },
  {
    index: 10,
    ourTitle: 'Writers',
    ytTitle: 'Net Cafe - 19961218 - NC112 - Writers',
    url: 'https://www.youtube.com/watch?v=W8lT3U7MIfo',
  },
  {
    index: 13,
    ourTitle: 'Electronic Communities',
    ytTitle: '',
    url: '',
  },
  {
    index: 14,
    ourTitle: 'Weird Science',
    ytTitle: 'Net Cafe: Weird Science On The Web (1996)',
    url: 'https://www.youtube.com/watch?v=hqCZPT_QCPw',
  },
  {
    index: 15,
    ourTitle: 'Travel Sites Online',
    ytTitle: 'Net Cafe: Travel Sites Online (1997)',
    url: 'https://www.youtube.com/watch?v=zPO7DDbnXOk',
  },
  {
    index: 16,
    ourTitle: 'Equality and Diversity',
    ytTitle: 'Net Cafe - 19970228 - NC0109 - Equality and Diversity',
    url: 'https://www.youtube.com/watch?v=S6eOeE8LYqM',
  },
  {
    index: 17,
    ourTitle: 'Religion',
    ytTitle: '',
    url: '',
  },
  {
    index: 19,
    ourTitle: 'Health Sites',
    ytTitle: 'Net Cafe: Health Sites (1996)',
    url: 'https://www.youtube.com/watch?v=oT8Vy8uAApk',
  },
  {
    index: 20,
    ourTitle: 'TV Shows Online',
    ytTitle: 'Net Cafe - TV Shows Online (1997)',
    url: 'https://www.youtube.com/watch?v=wNlBHc8cluo',
  },
  {
    index: 21,
    ourTitle: 'Censorship Online',
    ytTitle: 'Net Cafe: Censorship Online (1997)',
    url: 'https://www.youtube.com/watch?v=jsDxdEvkZgg',
  },
  {
    index: 22,
    ourTitle: 'Online Sports',
    ytTitle: 'Net Cafe: Online Sports (1997)',
    url: 'https://www.youtube.com/watch?v=RyUosKB7Clk',
  },
  {
    index: 23,
    ourTitle: 'Privacy in Cyberspace',
    ytTitle: 'Net Cafe: Privacy In Cyberspace (1997)',
    url: 'https://www.youtube.com/watch?v=vLfO-Uffx8Y',
  },
  {
    index: 24,
    ourTitle: 'Science Fiction Online',
    ytTitle: 'Net Cafe: Science Fiction Online (1997)',
    url: 'https://www.youtube.com/watch?v=uS4pMDp4GyE',
  },
  {
    index: 26,
    ourTitle: 'Virtual Doctors',
    ytTitle: 'Net Cafe: Virtual Doctors',
    url: 'https://www.youtube.com/watch?v=1LcLc4ABKEg',
  },
  {
    index: 27,
    ourTitle: 'Web Radio',
    ytTitle: 'Net Cafe - Web Radio (1997)',
    url: 'https://www.youtube.com/watch?v=2cKLe0EUufY',
  },
  {
    index: 28,
    ourTitle: 'Webby Awards 1997',
    ytTitle: 'Net Cafe: Webby Awards 1997 (1997)',
    url: 'https://www.youtube.com/watch?v=CKTUo1yTjpo',
  },
  {
    index: 30,
    ourTitle: 'Online Sports',
    ytTitle: 'Net Cafe: Online Sports (1997)',
    url: 'https://www.youtube.com/watch?v=RyUosKB7Clk',
  },
  {
    index: 31,
    ourTitle: 'Privacy in Cyberspace',
    ytTitle: 'Net Cafe: Privacy In Cyberspace (1997)',
    url: 'https://www.youtube.com/watch?v=vLfO-Uffx8Y',
  },
  {
    index: 32,
    ourTitle: 'Web Radio',
    ytTitle: 'Net Cafe - Web Radio (1997)',
    url: 'https://www.youtube.com/watch?v=2cKLe0EUufY',
  },
  {
    index: 35,
    ourTitle: 'War on the Web',
    ytTitle: 'Net Cafe: War On The Web (1998)',
    url: 'https://www.youtube.com/watch?v=Xqu_PSoyG0E',
  },
  {
    index: 36,
    ourTitle: 'Chat Rooms',
    ytTitle: 'Net Cafe - Chat Rooms (1998)',
    url: 'https://www.youtube.com/watch?v=lKIEI31aMHQ',
  },
  {
    index: 38,
    ourTitle: 'Cyber News',
    ytTitle: 'Net Cafe - 20000303 - NC410 - Cyber News',
    url: 'https://www.youtube.com/watch?v=GgIBK1qT-3k',
  },
  {
    index: 41,
    ourTitle: 'Gambling and Gaming on the Web',
    ytTitle: 'Net Cafe: Gambling And Gaming On The Web (1998)',
    url: 'https://www.youtube.com/watch?v=xWU7hlkbAuM',
  },
  {
    index: 42,
    ourTitle: 'Games on the Net',
    ytTitle: 'Net Cafe - Games on the Net -  #106 - 1998',
    url: 'https://www.youtube.com/watch?v=ifEfswM1rpk',
  },
  {
    index: 43,
    ourTitle: 'Home Improvement 1998',
    ytTitle: 'Net Cafe: Home Improvement (1998)',
    url: 'https://www.youtube.com/watch?v=2A4uCMPICxo',
  },
  {
    index: 44,
    ourTitle: 'Investing Online 1998',
    ytTitle: 'Net Cafe: Investing Online (1998)',
    url: 'https://www.youtube.com/watch?v=EL1wQ8ew8_c',
  },
  {
    index: 46,
    ourTitle: 'Safe Kids Safe Net',
    ytTitle: '',
    url: '',
  },
  {
    index: 47,
    ourTitle: 'Small Business Resources on the Net',
    ytTitle: 'Net Cafe: Small Business Resources On The Net (1998)',
    url: 'https://www.youtube.com/watch?v=bslm9Fu9xXI',
  },
  {
    index: 48,
    ourTitle: 'Space Science',
    ytTitle: 'Net Cafe - 19980501 - NC218 - Space Science',
    url: 'https://www.youtube.com/watch?v=pp8JCoBomoU',
  },
  {
    index: 49,
    ourTitle: 'The Global Net',
    ytTitle: 'Net Cafe: The Global Net (1998)',
    url: 'https://www.youtube.com/watch?v=KkBNzoh5uVs',
  },
  {
    index: 50,
    ourTitle: 'TV Shows Online',
    ytTitle: 'Net Cafe - TV Shows Online (1997)',
    url: 'https://www.youtube.com/watch?v=wNlBHc8cluo',
  },
  {
    index: 51,
    ourTitle: 'Finding Anyone  Anything Online',
    ytTitle: 'Net Cafe: Finding Anyone / Anything Online (1998)',
    url: 'https://www.youtube.com/watch?v=rTYCHRDUpEg',
  },
  {
    index: 52,
    ourTitle: 'Best SOHO Resources',
    ytTitle: 'Net Cafe - 19980522 - NC221 - Best SOHO Resources',
    url: 'https://www.youtube.com/watch?v=QoCfNM1TyKA',
  },
  {
    index: 54,
    ourTitle: 'Humor on the Web',
    ytTitle: 'Net Cafe - Humor on the Web (1998)',
    url: 'https://www.youtube.com/watch?v=G7_26HK1hrA',
  },
  {
    index: 55,
    ourTitle: 'Group Therapy Net Style 1998',
    ytTitle: 'Net Cafe: Group Therapy Net Style (1998)',
    url: 'https://www.youtube.com/watch?v=2abDZBdwBIk',
  },
  {
    index: 57,
    ourTitle: 'Jobs and Careers',
    ytTitle: 'Net Cafe: Jobs And Careers (1998)',
    url: 'https://www.youtube.com/watch?v=QT0kwTWCyQw',
  },
  {
    index: 58,
    ourTitle: 'The Hollywood Connection',
    ytTitle: 'Net Cafe - 19980814 - NC233 - The Hollywood Connection',
    url: 'https://www.youtube.com/watch?v=fQ1f7wuPRrk',
  },
  {
    index: 59,
    ourTitle: 'Sex Online',
    ytTitle: 'Net Cafe: Sex Online (1998)',
    url: 'https://www.youtube.com/watch?v=oZzIJmvDZxo',
  },
  {
    index: 60,
    ourTitle: 'Cool Home Pages',
    ytTitle: 'Net Cafe - Cool Home Pages (1998)',
    url: 'https://www.youtube.com/watch?v=BiotWasglAw',
  },
  {
    index: 61,
    ourTitle: 'Making Money On Line',
    ytTitle: 'Net Cafe: Making Money Online (1998)',
    url: 'https://www.youtube.com/watch?v=S-dp_yu5JbI',
  },
  {
    index: 62,
    ourTitle: 'Portals',
    ytTitle: 'Net Cafe: Portals (1998)',
    url: 'https://www.youtube.com/watch?v=z4xoMekwShQ',
  },
  {
    index: 63,
    ourTitle: 'Space Science',
    ytTitle: 'Net Cafe - 19980501 - NC218 - Space Science',
    url: 'https://www.youtube.com/watch?v=pp8JCoBomoU',
  },
  {
    index: 64,
    ourTitle: 'Incredibly Useful Sites',
    ytTitle: 'Powerful Website you Should Know!',
    url: 'https://www.youtube.com/watch?v=OFUszRLmrsc',
  },
  {
    index: 65,
    ourTitle: 'Online Literature',
    ytTitle: 'Net Cafe - Online Literature (1999)',
    url: 'https://www.youtube.com/watch?v=WMswE9eCHFk',
  },
  {
    index: 66,
    ourTitle: 'Adventure Travel Online',
    ytTitle: 'Net Cafe - 19991126 - NC348 - Adventure Travel',
    url: 'https://www.youtube.com/watch?v=WmorRTrQboA',
  },
  {
    index: 67,
    ourTitle: 'Crime and Justice',
    ytTitle: '',
    url: '',
  },
  {
    index: 68,
    ourTitle: 'Performing Arts on the Web',
    ytTitle: 'Net Cafe - 19990611 - NC324 - Performing Arts on the Web',
    url: 'https://www.youtube.com/watch?v=Uhc8i4JtjMk',
  },
  {
    index: 69,
    ourTitle: 'Lions and Tigers and Bears',
    ytTitle: '',
    url: '',
  },
  {
    index: 70,
    ourTitle: 'Hollywood on the Net',
    ytTitle: 'Net Cafe - 20000225 - NC409 - Hollywood on The Net',
    url: 'https://www.youtube.com/watch?v=yqTlEDyf_CQ',
  },
  {
    index: 71,
    ourTitle: 'Investing Online 1999',
    ytTitle: 'Net Cafe: Investing Online (1998)',
    url: 'https://www.youtube.com/watch?v=EL1wQ8ew8_c',
  },
  {
    index: 72,
    ourTitle: 'Lifelong Learning',
    ytTitle: '',
    url: '',
  },
  {
    index: 73,
    ourTitle: 'Just for Fun',
    ytTitle: '',
    url: '',
  },
  {
    index: 74,
    ourTitle: 'ECommerce',
    ytTitle: 'Net Cafe - E-Commerce (1999)',
    url: 'https://www.youtube.com/watch?v=ZNVEcGnx15k',
  },
  {
    index: 75,
    ourTitle: 'Conspiracy Theories 1999',
    ytTitle: 'Net Cafe: Conspiracy Theories (1999)',
    url: 'https://www.youtube.com/watch?v=QeBUkZjdbi0',
  },
  {
    index: 76,
    ourTitle: 'Cyber Kids',
    ytTitle: '',
    url: '',
  },
  {
    index: 78,
    ourTitle: 'Humor Online',
    ytTitle: 'Net Cafe - Humor Online (2000)',
    url: 'https://www.youtube.com/watch?v=oWBAkdJWyk8',
  },
  {
    index: 79,
    ourTitle: 'New Age Websites',
    ytTitle: 'Net Cafe - 19990716 - NC329 - New Age Sites',
    url: 'https://www.youtube.com/watch?v=TClAYYCYgKw',
  },
  {
    index: 80,
    ourTitle: 'Personal Investing Online',
    ytTitle: '',
    url: '',
  },
  {
    index: 81,
    ourTitle: 'Consumer Protection Online',
    ytTitle: 'Net Cafe - 19990903 - NC336 - Consumer Protection Online',
    url: 'https://www.youtube.com/watch?v=jr67d93mGxc',
  },
  {
    index: 82,
    ourTitle: 'Online Collecting',
    ytTitle: 'Net Cafe - 19990709 - NC328 - Online Collecting',
    url: 'https://www.youtube.com/watch?v=oBnGSthRkw4',
  },
  {
    index: 83,
    ourTitle: 'Webby Awards 1999  Part One',
    ytTitle: 'Net Cafe - 19990723 - NC330 - Webby Awards 1999 Part 1',
    url: 'https://www.youtube.com/watch?v=aC-HW8-E7Tg',
  },
  {
    index: 84,
    ourTitle: 'Webby Awards 1999  Part Two',
    ytTitle: 'Net Cafe  -19990730 - NC331 - Webby Awards 1999 Part 2',
    url: 'https://www.youtube.com/watch?v=idMd_5FUmqM',
  },
  {
    index: 85,
    ourTitle: 'Online Job Hunting',
    ytTitle: 'How to Find Companies ACTUALLY Hiring',
    url: 'https://www.youtube.com/watch?v=TzGL1rNm05Y',
  },
  {
    index: 86,
    ourTitle: 'Entertainment on the Web',
    ytTitle: 'Net Cafe - 19980703 - NC227 - Humor on the Web',
    url: 'https://www.youtube.com/watch?v=pJTJ1bbXQnM',
  },
  {
    index: 87,
    ourTitle: 'Finding People Online',
    ytTitle: '',
    url: '',
  },
  {
    index: 89,
    ourTitle: 'Web Startups April 13th 2000',
    ytTitle: '',
    url: '',
  },
  {
    index: 90,
    ourTitle: 'Web Startups April 14th',
    ytTitle: '',
    url: '',
  },
  {
    index: 91,
    ourTitle: 'Web Startups May 5th',
    ytTitle: '',
    url: '',
  },
  {
    index: 92,
    ourTitle: 'Web Startups May 26th',
    ytTitle: '',
    url: '',
  },
  {
    index: 93,
    ourTitle: 'Grim Reaper Web Sites 2000',
    ytTitle: '',
    url: '',
  },
  {
    index: 94,
    ourTitle: 'Web Startups November 3rd',
    ytTitle: '',
    url: '',
  },
  {
    index: 96,
    ourTitle: 'Webby Awards 2000 Part One',
    ytTitle: '',
    url: '',
  },
  {
    index: 97,
    ourTitle: 'Webby Awards 2000 Part Two',
    ytTitle: '',
    url: '',
  },
  {
    index: 99,
    ourTitle: 'Interesting Web Sites',
    ytTitle: '',
    url: '',
  },
  {
    index: 100,
    ourTitle: 'New Web Sites',
    ytTitle: '',
    url: '',
  },
  {
    index: 101,
    ourTitle: 'State of the Web',
    ytTitle: '',
    url: '',
  },
  {
    index: 102,
    ourTitle: 'Web Startups March 9th',
    ytTitle: '',
    url: '',
  },
  {
    index: 103,
    ourTitle: 'Web Startups April 6th',
    ytTitle: '',
    url: '',
  },
  {
    index: 104,
    ourTitle: 'Web Startups April 13th 2001',
    ytTitle: '',
    url: '',
  },
  {
    index: 105,
    ourTitle: 'Web Startups April 20th',
    ytTitle: '',
    url: '',
  },
  {
    index: 106,
    ourTitle: 'Web Startups May 4th',
    ytTitle: '',
    url: '',
  },
  {
    index: 107,
    ourTitle: 'Web Startups May 11th',
    ytTitle: '',
    url: '',
  },
  {
    index: 108,
    ourTitle: 'Web Startups June 1st',
    ytTitle: '',
    url: '',
  },
  {
    index: 109,
    ourTitle: 'Web Startups June 8th',
    ytTitle: '',
    url: '',
  },
  {
    index: 110,
    ourTitle: 'Web Startups June 15th',
    ytTitle: '',
    url: '',
  },
  {
    index: 111,
    ourTitle: 'Web Startups June 29th',
    ytTitle: '',
    url: '',
  },
  {
    index: 112,
    ourTitle: 'Web Startups October 8th',
    ytTitle: '',
    url: '',
  },
  {
    index: 113,
    ourTitle: 'Web Startups October 20th',
    ytTitle: 'Net Cafe: Web StartUps - Oct 20, 2000',
    url: 'https://www.youtube.com/watch?v=1twivxrrxo0',
  },
  {
    index: 114,
    ourTitle: 'Web Startups December 1st',
    ytTitle: '',
    url: '',
  },
  {
    index: 115,
    ourTitle: 'Web Startups December 7th 2001',
    ytTitle: '',
    url: '',
  },
  {
    index: 116,
    ourTitle: 'Web Startups December 14th',
    ytTitle: '',
    url: '',
  },
  {
    index: 117,
    ourTitle: 'Home Improvement 2002',
    ytTitle: '',
    url: '',
  },
  {
    index: 118,
    ourTitle: 'Nicholas Negroponte Part One',
    ytTitle: '',
    url: '',
  },
  {
    index: 119,
    ourTitle: 'Nicholas Negroponte Part Two',
    ytTitle: '',
    url: '',
  },
  {
    index: 120,
    ourTitle: 'State of the Web',
    ytTitle: '',
    url: '',
  },
  {
    index: 121,
    ourTitle: 'Web Startups January 4th',
    ytTitle: '',
    url: '',
  },
  {
    index: 122,
    ourTitle: 'Web Startups January 11th',
    ytTitle: '',
    url: '',
  },
  {
    index: 123,
    ourTitle: 'Web Startups February 15th',
    ytTitle: '',
    url: '',
  },
  {
    index: 124,
    ourTitle: 'Web Startups February 22nd',
    ytTitle: '',
    url: '',
  },
  {
    index: 125,
    ourTitle: 'Group Therapy Net Style 2002',
    ytTitle: '',
    url: '',
  },
];
