/*
youtubeURL: null,
    internetArchiveURL: [ null ],
    framesURL: [ null ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
    
    {
      index: 0,
      season: 1996,
      episodeOfSeason: 1,
      titles: [''],
      date: '1996',
    },
 
    {
      '1996': 10,
      '1997': 23,
      '1998': 30,
      '1999': 21,
      '2000': 11,
      '2001': 17,
      '2002': 7,
    }
*/

const netcafeEpisodes = [
  {
    index: 1,
    season: '1996',
    episodeOfSeason: 1,
    titles: ['Hackers', 'Hackers'],
    date: 844210800000,
    youtubeURL:
      'https://www.youtube.com/watch?v=le7XO7EAYO0&pp=ygUPbmV0Y2FmZSBoYWNrZXJz',
    internetArchiveURL: ['https://archive.org/details/nc101_hackers'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc101_hackers',
    ],
    watched: true,
    streamTitle: 'FAT 32 QUICK BLAST',
    streamDate: 1666220400000,
    streamURL: 'https://www.youtube.com/watch?v=CpZC91gwpUw',
  },
  {
    index: 2,
    season: '1996',
    episodeOfSeason: 2,
    titles: ["UFO's", 'UFOs'],
    date: 844815600000,
    youtubeURL:
      'https://www.youtube.com/watch?v=87U5b-yiuNE&pp=ygUMbmV0Y2FmZSB1Zm9z',
    internetArchiveURL: ['https://archive.org/details/nc102_ufos'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc102_ufos',
    ],
    watched: true,
    streamTitle: 'FAT 32 QUICKBLAST',
    streamDate: 1630191600000,
    streamURL: 'https://www.youtube.com/watch?v=erRqLICGTV8',
  },
  {
    index: 3,
    season: '1996',
    episodeOfSeason: 3,
    titles: ['Politics on the Web', 'Politics on the Web'],
    date: 845506800000,
    youtubeURL:
      'https://www.youtube.com/watch?v=j4jX0-tyKy0&pp=ygUbbmV0Y2FmZSBwb2xpdGljcyBvbiB0aGUgd2Vi',
    internetArchiveURL: ['https://archive.org/details/nc103_cyberpolitics'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc103_cyberpolitics',
    ],
    watched: true,
    streamTitle: 'More Disturbance',
    streamDate: 1730937600000,
    streamURL: 'https://www.youtube.com/watch?v=MugtdW2NP-E',
  },
  {
    index: 4,
    season: '1996',
    episodeOfSeason: 4,
    titles: ['Dark Side of the Net', 'The Dark Side of the Web'],
    date: 845938800000,
    youtubeURL:
      'https://www.youtube.com/watch?v=zW_saOw0lAs&pp=ygUcbmV0Y2FmZSBkYXJrIHNpZGUgb2YgdGhlIHdlYg%3D%3D',
    internetArchiveURL: [
      'https://archive.org/details/nc104_dark_side_of_the_net',
    ],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc104_dark_side_of_the_net',
    ],
    watched: true,
    streamTitle: 'StreamZONE',
    streamDate: 1705881600000,
    streamURL: 'https://www.youtube.com/watch?v=qRwHNaFhsEI',
  },
  {
    index: 5,
    season: '1996',
    episodeOfSeason: 5,
    titles: ['Women on the Web', 'Women on the Web'],
    date: 846460800000,
    youtubeURL: 'https://www.youtube.com/watch?v=4Ii94pqIbDA',
    internetArchiveURL: ['https://archive.org/details/nc105_women'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc105_women',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 6,
    season: '1996',
    episodeOfSeason: 6,
    titles: ['Games', 'Games on the Net'],
    date: 847065600000,
    youtubeURL: 'https://www.youtube.com/watch?v=yPbmMczw1K0',
    internetArchiveURL: ['https://archive.org/details/nc106_games'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc106_games',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 7,
    season: '1996',
    episodeOfSeason: 7,
    titles: ['The 3D Web', 'The 3D Web'],
    date: 847843200000,
    youtubeURL: 'https://www.youtube.com/watch?v=Z5WubOHkgew',
    internetArchiveURL: ['https://archive.org/details/nc107_vrml3d_worlds'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc107_vrml3d_worlds',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 8,
    season: '1996',
    episodeOfSeason: 8,
    titles: ['Music', 'Music Web Sites'],
    date: 848275200000,
    youtubeURL: 'https://www.youtube.com/watch?v=S86sJx16Xso',
    internetArchiveURL: ['https://archive.org/details/nc110_music'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc110_music',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 9,
    season: '1996',
    episodeOfSeason: 9,
    titles: ['Movies', 'Movies Online'],
    date: 849571200000,
    youtubeURL: 'https://www.youtube.com/watch?v=NL299SC8zO8',
    internetArchiveURL: ['https://archive.org/details/nc111_movies'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc111_movies',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 10,
    season: '1996',
    episodeOfSeason: 10,
    titles: ['Writers', 'Cyber Writing'],
    date: 850867200000,
    youtubeURL: 'https://www.youtube.com/watch?v=W8lT3U7MIfo',
    internetArchiveURL: ['https://archive.org/details/nc112_writers'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc112_writers',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 11,
    season: '1997',
    episodeOfSeason: 1,
    titles: ['Love and Romance on the Web', 'Love and Romance on the Web'],
    date: 853459200000,
    youtubeURL:
      'https://www.youtube.com/watch?v=fcdHdpo2bHk&pp=ygUUbmV0Y2FmZSBsb3ZlIHJvbWFuY2U%3D',
    internetArchiveURL: ['https://archive.org/details/nc103_dating_romance'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc103_dating_romance',
    ],
    watched: true,
    streamTitle: 'Silent Hill 2 - Part 4',
    streamDate: 1670803200000,
    streamURL: 'https://www.youtube.com/watch?v=axkKe_lfVdQ',
  },
  {
    index: 12,
    season: '1997',
    episodeOfSeason: 2,
    titles: ['Art on the Net', 'Art on the Net'],
    date: 854064000000,
    youtubeURL:
      'https://www.youtube.com/watch?v=8EO-wYd3LfM&pp=ygUWbmV0Y2FmZSBhcnQgb24gdGhlIG5ldA%3D%3D',
    internetArchiveURL: ['https://archive.org/details/nc104_art'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc104_art',
    ],
    watched: true,
    streamTitle: 'Unending Cruelty 2025',
    streamDate: 1736035200000,
    streamURL: 'https://www.youtube.com/watch?v=phrYsVgQRs0',
  },
  {
    index: 13,
    season: '1997',
    episodeOfSeason: 3,
    titles: ['Electronic Communities', 'Electronic Communities'],
    date: 854668800000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 14,
    season: '1997',
    episodeOfSeason: 4,
    titles: ['Weird Science', 'Weird Science on the Web'],
    date: 855792000000,
    youtubeURL: 'https://www.youtube.com/watch?v=hqCZPT_QCPw',
    internetArchiveURL: ['https://archive.org/details/nc107_weird_science'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc107_weird_science',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 15,
    season: '1997',
    episodeOfSeason: 5,
    titles: ['Travel Sites Online', 'Travel Sites Online'],
    date: 856483200000,
    youtubeURL: 'https://www.youtube.com/watch?v=zPO7DDbnXOk',
    internetArchiveURL: ['https://archive.org/details/nc108_travel'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc108_travel',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 16,
    season: '1997',
    episodeOfSeason: 6,
    titles: ['Equality and Diversity', 'Equality & Diversity On Line'],
    date: 857088000000,
    youtubeURL: 'https://www.youtube.com/watch?v=S6eOeE8LYqM',
    internetArchiveURL: [
      'https://archive.org/details/nc109_equality-diversity',
    ],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc109_equality-diversity',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 17,
    season: '1997',
    episodeOfSeason: 7,
    titles: ['Religion', 'Religion'],
    date: 858297600000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 18,
    season: '1997',
    episodeOfSeason: 8,
    titles: ['Disinformation on the Web', 'Disinformation on the Web'],
    date: 858902400000,
    youtubeURL:
      'https://www.youtube.com/watch?v=wOwv9vR6hQI&pp=ygUWbmV0Y2FmZSBkaXNpbmZvcm1hdGlvbg%3D%3D',
    internetArchiveURL: ['https://archive.org/details/nc119_disinformation'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc119_disinformation',
    ],
    watched: true,
    streamTitle: 'StreamZONE',
    streamDate: 1709683200000,
    streamURL: 'https://www.youtube.com/watch?v=M-o_ppS1pNI',
  },
  {
    index: 19,
    season: '1997',
    episodeOfSeason: 9,
    titles: ['Health Sites', 'Health Sites'],
    date: 859507200000,
    youtubeURL: 'https://www.youtube.com/watch?v=oT8Vy8uAApk',
    internetArchiveURL: ['https://archive.org/details/nc113_health'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc113_health',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 20,
    season: '1997',
    episodeOfSeason: 10,
    titles: ['TV Shows Online', 'TV Shows Online'],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=wNlBHc8cluo',
    internetArchiveURL: ['https://archive.org/details/TVshowso98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_TVshowso98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 21,
    season: '1997',
    episodeOfSeason: 11,
    titles: ['Censorship Online', 'Censorship Online'],
    date: 826761600000,
    youtubeURL: 'https://www.youtube.com/watch?v=jsDxdEvkZgg',
    internetArchiveURL: ['https://archive.org/details/nc111_censorship'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc111_censorship',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 21,
    season: '1997',
    episodeOfSeason: 11.5,
    titles: ['Weird Web', 'The Weird Web'],
    date: 861922800000,
    youtubeURL: 'https://www.youtube.com/watch?v=jsDxdEvkZgg',
    internetArchiveURL: ['https://archive.org/details/nc117_weird_web'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc117_weird_web',
    ],
    watched: true,
    streamTitle: 'New Vegas (Pt.3) quickblast',
    streamDate: 1712444400000,
    streamURL: 'https://www.youtube.com/watch?v=tJ7ES9NJDIU',
  },
  {
    index: 22,
    season: '1997',
    episodeOfSeason: 12,
    titles: ['Online Sports', 'Online Sports'],
    date: 880675200000,
    youtubeURL: 'https://www.youtube.com/watch?v=RyUosKB7Clk',
    internetArchiveURL: ['https://archive.org/details/OnlineSp1997'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_OnlineSp1997',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 23,
    season: '1997',
    episodeOfSeason: 13,
    titles: ['Privacy in Cyberspace', 'Privacy in Cyberspace'],
    date: 883094400000,
    youtubeURL: 'https://www.youtube.com/watch?v=vLfO-Uffx8Y',
    internetArchiveURL: ['https://archive.org/details/privacyi97'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_privacyi97',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 24,
    season: '1997',
    episodeOfSeason: 14,
    titles: ['Science Fiction Online', 'Science Fiction Online'],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=uS4pMDp4GyE',
    internetArchiveURL: ['https://archive.org/details/nc118_scifi'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc118_scifi',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 25,
    season: '1997',
    episodeOfSeason: 15,
    titles: ['The Virtual Zoo', 'The Virtual Zoo'],
    date: 880070400000,
    youtubeURL:
      'https://www.youtube.com/watch?v=GI_6AW4jI2o&pp=ygULbmV0Y2FmZSB6b28%3D',
    internetArchiveURL: ['https://archive.org/details/nc147_virtual_zoo'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc147_virtual_zoo',
    ],
    watched: true,
    streamTitle: 'Roachzone Part 2',
    streamDate: 1706832000000,
    streamURL: 'https://www.youtube.com/watch?v=NbXF06F-e9E',
  },
  {
    index: 26,
    season: '1997',
    episodeOfSeason: 17,
    titles: ['Virtual Doctors', 'Virtual Doctors'],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=1LcLc4ABKEg',
    internetArchiveURL: ['https://archive.org/details/nc216_virtual_doctor'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc216_virtual_doctor',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 27,
    season: '1997',
    episodeOfSeason: 18,
    titles: ['Web Radio', 'Web Radio'],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=2cKLe0EUufY',
    internetArchiveURL: ['https://archive.org/details/webradio97'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_webradio97',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 28,
    season: '1997',
    episodeOfSeason: 19,
    titles: ['Webby Awards 1997', 'Webby Awards 1997'],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=CKTUo1yTjpo',
    internetArchiveURL: ['https://archive.org/details/nc112_webby_awards'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc112_webby_awards',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 29,
    season: '1997',
    episodeOfSeason: 20,
    titles: ['Comic Books on the Web', 'Comic Books on the Web'],
    date: 852854400000,
    youtubeURL:
      'https://www.youtube.com/watch?v=ZwnYvwjvw3s&pp=ygUebmV0Y2FmZSBjb21pYyBib29rcyBvbiB0aGUgd2Vi',
    internetArchiveURL: ['https://archive.org/details/nc102_comics'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc102_comics',
    ],
    watched: true,
    streamTitle: 'FAT 32 QUICK BLAST - CHEIFEIT-M (A.M.)',
    streamDate: 1671494400000,
    streamURL: 'https://www.youtube.com/watch?v=p1dc-7pkXlk',
  },
  {
    index: 30,
    season: '1997',
    episodeOfSeason: 21,
    titles: ['Online Sports', 'Online Sports'],
    date: 880675200000,
    youtubeURL: 'https://www.youtube.com/watch?v=RyUosKB7Clk',
    internetArchiveURL: ['https://archive.org/details/OnlineSp1997'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_OnlineSp1997',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 31,
    season: '1997',
    episodeOfSeason: 22,
    titles: ['Privacy in Cyberspace', 'Privacy in Cyberspace'],
    date: 877647600000,
    youtubeURL: 'https://www.youtube.com/watch?v=vLfO-Uffx8Y',
    internetArchiveURL: ['https://archive.org/details/privacyi97'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_privacyi97',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 32,
    season: '1997',
    episodeOfSeason: 23,
    titles: ['Web Radio', 'Web Radio'],
    date: 877042800000,
    youtubeURL: 'https://www.youtube.com/watch?v=2cKLe0EUufY',
    internetArchiveURL: ['https://archive.org/details/webradio97'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_webradio97',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 34,
    season: '1998',
    episodeOfSeason: 1,
    titles: ['Voyeurism Online', 'Voyeurism Online:'],
    date: 885513600000,
    youtubeURL:
      'https://www.youtube.com/watch?v=axO-kncTDgQ&pp=ygURbmV0Y2FmZSB2b3lldXJpc20%3D',
    internetArchiveURL: ['https://archive.org/details/Voyerism00'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Voyerism00',
    ],
    watched: true,
    streamTitle: 'Resident Evil Village F.C. est. 1894',
    streamDate: 1630018800000,
    streamURL: 'https://www.youtube.com/watch?v=8x8kNFjpwsE',
  },
  {
    index: 35,
    season: '1998',
    episodeOfSeason: 2,
    titles: ['War on the Web', 'War On The Web'],
    date: 887932800000,
    youtubeURL: 'https://www.youtube.com/watch?v=Xqu_PSoyG0E',
    internetArchiveURL: ['https://archive.org/details/WarOnThe00'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_WarOnThe00',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 36,
    season: '1998',
    episodeOfSeason: 3,
    titles: ['Chat Rooms', 'Chat Rooms'],
    date: 907887600000,
    youtubeURL: 'https://www.youtube.com/watch?v=lKIEI31aMHQ',
    internetArchiveURL: ['https://archive.org/details/ChatRoom00'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_ChatRoom00',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 37,
    season: '1998',
    episodeOfSeason: 6,
    titles: ['Cyber Communities', 'Cyber Communities'],
    date: null,
    youtubeURL:
      'https://www.youtube.com/watch?v=axO-kncTDgQ&pp=ygURbmV0Y2FmZSB2b3lldXJpc20%3D',
    internetArchiveURL: ['https://archive.org/details/CyberCom99'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_CyberCom99',
    ],
    watched: true,
    streamTitle: 'Resident Stephen 3 (pt. 2)',
    streamDate: 1711324800000,
    streamURL: 'https://www.youtube.com/watch?v=1ej4D13UyqM',
  },
  {
    index: 38,
    season: '1998',
    episodeOfSeason: 7,
    titles: ['Cyber News', 'Cyber News'],
    date: 888883200000,
    youtubeURL: 'https://www.youtube.com/watch?v=GgIBK1qT-3k',
    internetArchiveURL: ['https://archive.org/details/CyberNew00'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_CyberNew00',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 39,
    season: '1998',
    episodeOfSeason: 8,
    titles: ['Cyber Sports', 'Cyber Sports'],
    date: null,
    youtubeURL:
      'https://www.youtube.com/watch?v=facILPyMEJM&pp=ygUUbmV0Y2FmZSBjeWJlciBzcG9ydHM%3D',
    internetArchiveURL: ['https://archive.org/details/CyberSpo99'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_CyberSpo99',
    ],
    watched: true,
    streamTitle: 'Roachzone Part 2',
    streamDate: 1706832000000,
    streamURL: 'https://www.youtube.com/watch?v=NbXF06F-e9E',
  },
  {
    index: 40,
    season: '1998',
    episodeOfSeason: 9,
    titles: ['Buy It Online', 'Buy It Online'],
    date: 889747200000,
    youtubeURL:
      'https://www.youtube.com/watch?v=zh9cFHV7Ei0&pp=ygUVbmV0Y2FmZSBidXkgaXQgb25saW5l',
    internetArchiveURL: ['https://archive.org/details/Buyitonl98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Buyitonl98',
    ],
    watched: true,
    streamTitle: 'Cruel Situations',
    streamDate: 1733270400000,
    streamURL: 'https://www.youtube.com/watch?v=VGyDS8ag0zM',
  },
  {
    index: 41,
    season: '1998',
    episodeOfSeason: 10,
    titles: [
      'Gambling and Gaming on the Web',
      'Gambling and Gaming on the Web',
    ],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=xWU7hlkbAuM',
    internetArchiveURL: ['https://archive.org/details/nc428_gambling_games'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc428_gambling_games',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 42,
    season: '1998',
    episodeOfSeason: 11,
    titles: ['Games on the Net', 'Games on the Net'],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=ifEfswM1rpk',
    internetArchiveURL: ['https://archive.org/details/nc106_games'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc106_games',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 43,
    season: '1998',
    episodeOfSeason: 14,
    titles: ['Home Improvement (1998)', 'Home Improvement'],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=2A4uCMPICxo',
    internetArchiveURL: ['https://archive.org/details/nc231_home_improvement'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc231_home_improvement',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 44,
    season: '1998',
    episodeOfSeason: 16,
    titles: ['Investing Online (1998)', 'Investing Online'],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=EL1wQ8ew8_c',
    internetArchiveURL: ['https://archive.org/details/Investin1998'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Investin1998',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 45,
    season: '1998',
    episodeOfSeason: 19,
    titles: ['Online Activism', 'Online Activism'],
    date: null,
    youtubeURL:
      'https://www.youtube.com/watch?v=65t7tg3g0oY&pp=ygUQbmV0Y2FmZSBhY3RpdmlzbQ%3D%3D',
    internetArchiveURL: ['https://archive.org/details/nc217_online_activism'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc217_online_activism',
    ],
    watched: true,
    streamTitle: 'THE END OF SILENT HILL 3',
    streamDate: 1736121600000,
    streamURL: 'https://www.youtube.com/watch?v=W2WJNgdAGHM',
  },
  {
    index: 46,
    season: '1998',
    episodeOfSeason: 21,
    titles: ['Safe Kids Safe Net', 'Safe Kids Safe Net'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/SafeKids2002'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_SafeKids2002',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 47,
    season: '1998',
    episodeOfSeason: 23,
    titles: [
      'Small Business Resources on the Net',
      'Small Business Resources On the Net',
    ],
    date: 895791600000,
    youtubeURL: 'https://www.youtube.com/watch?v=bslm9Fu9xXI',
    internetArchiveURL: ['https://archive.org/details/BestSOHO98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_BestSOHO98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 48,
    season: '1998',
    episodeOfSeason: 24,
    titles: ['Space Science', 'Space Science'],
    date: 893977200000,
    youtubeURL: 'https://www.youtube.com/watch?v=pp8JCoBomoU',
    internetArchiveURL: ['https://archive.org/details/SpaceSci98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_SpaceSci98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 49,
    season: '1998',
    episodeOfSeason: 25,
    titles: ['The Global Net', 'The Global Net'],
    date: 910915200000,
    youtubeURL: 'https://www.youtube.com/watch?v=KkBNzoh5uVs',
    internetArchiveURL: ['https://archive.org/details/GlobalNe99'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_GlobalNe99',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 50,
    season: '1998',
    episodeOfSeason: 29,
    titles: ['TV Shows Online', 'TV Shows Online'],
    date: 878256000000,
    youtubeURL: 'https://www.youtube.com/watch?v=wNlBHc8cluo',
    internetArchiveURL: ['https://archive.org/details/TVshowso98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_TVshowso98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 51,
    season: '1998',
    episodeOfSeason: 30,
    titles: [
      'Finding Anyone / Anything Online',
      'Finding Anyone / Anything Online',
    ],
    date: 886118400000,
    youtubeURL: 'https://www.youtube.com/watch?v=rTYCHRDUpEg',
    internetArchiveURL: ['https://archive.org/details/Findinga98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Findinga98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 52,
    season: '1998',
    episodeOfSeason: 32,
    titles: ['Best SOHO Resources', 'Small Business Resources On the Net'],
    date: 895791600000,
    youtubeURL: 'https://www.youtube.com/watch?v=QoCfNM1TyKA',
    internetArchiveURL: ['https://archive.org/details/BestSOHO98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_BestSOHO98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 53,
    season: '1998',
    episodeOfSeason: 33,
    titles: ['Grim Reaper Web Sites (1998)', 'Grim Reaper Web Sites (1998)'],
    date: 898815600000,
    youtubeURL:
      'https://www.youtube.com/watch?v=lOGh_6xmiWc&pp=ygUTbmV0Y2FmZSBncmltIHJlYXBlcg%3D%3D',
    internetArchiveURL: ['https://archive.org/details/GrimReap98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_GrimReap98',
    ],
    watched: true,
    streamTitle: 'FACE of WAR: Chaos Theory',
    streamDate: 1710460800000,
    streamURL: 'https://www.youtube.com/watch?v=TnZWb6DMPoE',
  },
  {
    index: 54,
    season: '1998',
    episodeOfSeason: 34,
    titles: ['Humor on the Web', 'Humor on the Web'],
    date: 899420400000,
    youtubeURL: 'https://www.youtube.com/watch?v=G7_26HK1hrA',
    internetArchiveURL: ['https://archive.org/details/HumorOnT98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_HumorOnT98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 55,
    season: '1998',
    episodeOfSeason: 35,
    titles: [
      'Group Therapy Net Style (1998)',
      'Group Therapy Net Style (1998)',
    ],
    date: 900630000000,
    youtubeURL: 'https://www.youtube.com/watch?v=2abDZBdwBIk',
    internetArchiveURL: ['https://archive.org/details/GroupThe98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_GroupThe98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 56,
    season: '1998',
    episodeOfSeason: 36,
    titles: ['Cyber Chat', 'Cyber Chat'],
    date: 901234800000,
    youtubeURL:
      'https://www.youtube.com/watch?v=65ipkhgZ58o&pp=ygUSbmV0Y2FmZSBjeWJlciBjaGF0',
    internetArchiveURL: ['https://archive.org/details/CyberCha98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_CyberCha98',
    ],
    watched: true,
    streamTitle: 'FAT 32 QUICK BLAST LISP MICROPHONE FILTER EXTREME EDITION',
    streamDate: 1665529200000,
    streamURL: 'https://www.youtube.com/watch?v=f_0mBHx6afc',
  },
  {
    index: 57,
    season: '1998',
    episodeOfSeason: 37,
    titles: ['Jobs and Careers', 'Jobs and Careers'],
    date: 902444400000,
    youtubeURL: 'https://www.youtube.com/watch?v=QT0kwTWCyQw',
    internetArchiveURL: ['https://archive.org/details/JobsandC98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_JobsandC98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 58,
    season: '1998',
    episodeOfSeason: 38,
    titles: ['The Hollywood Connection', 'The Hollywood Connection'],
    date: 903049200000,
    youtubeURL: 'https://www.youtube.com/watch?v=fQ1f7wuPRrk',
    internetArchiveURL: ['https://archive.org/details/Hollywoo98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Hollywoo98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 59,
    season: '1998',
    episodeOfSeason: 39,
    titles: ['Sex Online', 'Sex Online'],
    date: 904863600000,
    youtubeURL: 'https://www.youtube.com/watch?v=oZzIJmvDZxo',
    internetArchiveURL: ['https://archive.org/details/SexOnlin98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_SexOnlin98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 60,
    season: '1998',
    episodeOfSeason: 40,
    titles: ['Cool Home Pages', 'Cool Home Pages'],
    date: 906073200000,
    youtubeURL: 'https://www.youtube.com/watch?v=BiotWasglAw',
    internetArchiveURL: ['https://archive.org/details/CoolHome98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_CoolHome98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 61,
    season: '1998',
    episodeOfSeason: 41,
    titles: ['Making Money On Line', 'Making Money On Line'],
    date: 906678000000,
    youtubeURL: 'https://www.youtube.com/watch?v=S-dp_yu5JbI',
    internetArchiveURL: ['https://archive.org/details/Moneyont98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Moneyont98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 62,
    season: '1998',
    episodeOfSeason: 42,
    titles: ['Portals', 'Portals'],
    date: 911520000000,
    youtubeURL: 'https://www.youtube.com/watch?v=z4xoMekwShQ',
    internetArchiveURL: ['https://archive.org/details/Portals98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Portals98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 63,
    season: '1998',
    episodeOfSeason: 43,
    titles: ['Space Science', 'Space Science'],
    date: 893977200000,
    youtubeURL: 'https://www.youtube.com/watch?v=pp8JCoBomoU',
    internetArchiveURL: ['https://archive.org/details/SpaceSci98'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_SpaceSci98',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 64,
    season: '1999',
    episodeOfSeason: 1,
    titles: ['Incredibly Useful Sites', 'Incredibly Useful Sites'],
    date: 923612400000,
    youtubeURL: 'https://www.youtube.com/watch?v=OFUszRLmrsc',
    internetArchiveURL: ['https://archive.org/details/Incredib1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Incredib1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 65,
    season: '1999',
    episodeOfSeason: 2,
    titles: ['Online Literature', 'Online Literature'],
    date: 915753600000,
    youtubeURL: 'https://www.youtube.com/watch?v=WMswE9eCHFk',
    internetArchiveURL: ['https://archive.org/details/OnlineLi1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_OnlineLi1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 66,
    season: '1999',
    episodeOfSeason: 3,
    titles: ['Adventure Travel Online', 'Adventure Travel Online'],
    date: 916963200000,
    youtubeURL: 'https://www.youtube.com/watch?v=WmorRTrQboA',
    internetArchiveURL: ['https://archive.org/details/Adventur1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Adventur1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 67,
    season: '1999',
    episodeOfSeason: 4,
    titles: ['Crime and Justice', 'Crime and Justice'],
    date: 924822000000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/Crimeand1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Crimeand1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 68,
    season: '1999',
    episodeOfSeason: 5,
    titles: ['Performing Arts on the Web', 'Performing Arts on the Web'],
    date: 929055600000,
    youtubeURL: 'https://www.youtube.com/watch?v=Uhc8i4JtjMk',
    internetArchiveURL: ['https://archive.org/details/Performi1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Performi1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 69,
    season: '1999',
    episodeOfSeason: 6,
    titles: ['Lions and Tigers and Bears', 'Lions and Tigers and Bears'],
    date: 930265200000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/Lionsand1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Lionsand1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 70,
    season: '1999',
    episodeOfSeason: 7,
    titles: ['Hollywood on the Net', 'Hollywood on the Net'],
    date: 930870000000,
    youtubeURL: 'https://www.youtube.com/watch?v=yqTlEDyf_CQ',
    internetArchiveURL: ['https://archive.org/details/Hollywoo1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Hollywoo1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 71,
    season: '1999',
    episodeOfSeason: 8,
    titles: ['Investing Online (1999)', 'Investing Online (1999)'],
    date: 941760000000,
    youtubeURL: 'https://www.youtube.com/watch?v=EL1wQ8ew8_c',
    internetArchiveURL: ['https://archive.org/details/Investin1998'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Investin1998',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 72,
    season: '1999',
    episodeOfSeason: 9,
    titles: ['Lifelong Learning', 'Lifelong Learning'],
    date: 938732400000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/Lifelong1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Lifelong1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 73,
    season: '1999',
    episodeOfSeason: 10,
    titles: ['Just for Fun', 'Fun Web Sites'],
    date: 939337200000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/JustforF1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_JustforF1999',
    ],
    watched: true,
    streamTitle: 'StreamZONE',
    streamDate: 1705881600000,
    streamURL: 'https://www.youtube.com/watch?v=qRwHNaFhsEI',
  },
  {
    index: 74,
    season: '1999',
    episodeOfSeason: 11,
    titles: ['E-Commerce', 'E-Commerce'],
    date: 940546800000,
    youtubeURL: 'https://www.youtube.com/watch?v=ZNVEcGnx15k',
    internetArchiveURL: ['https://archive.org/details/ECommerc1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_ECommerc1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 75,
    season: '1999',
    episodeOfSeason: 12,
    titles: ['Conspiracy Theories (1999)', 'Conspiracy Theories (1999)'],
    date: 940546800000,
    youtubeURL: 'https://www.youtube.com/watch?v=QeBUkZjdbi0',
    internetArchiveURL: ['https://archive.org/details/Conspira1999'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Conspira1999',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 76,
    season: '1999',
    episodeOfSeason: 13,
    titles: ['Cyber Kids', 'Cyber Kids'],
    date: 945129600000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 77,
    season: '1999',
    episodeOfSeason: 14,
    titles: ['Xtreme Web', 'Extreme Web'],
    date: 945734400000,
    youtubeURL:
      'https://www.youtube.com/watch?v=ATxuqGRUWdM&pp=ygUObmV0Y2FmZSB4dHJlbWU%3D',
    internetArchiveURL: ['https://archive.org/details/nc351_xtreme_web'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc351_xtreme_web',
    ],
    watched: true,
    streamTitle: 'Resident Stephen 3 (pt. 2)',
    streamDate: 1711324800000,
    streamURL: 'https://www.youtube.com/watch?v=1ej4D13UyqM',
  },
  {
    index: 78,
    season: '1999',
    episodeOfSeason: 15,
    titles: ['Humor Online', 'Humor Online'],
    date: 946339200000,
    youtubeURL: 'https://www.youtube.com/watch?v=oWBAkdJWyk8',
    internetArchiveURL: ['https://archive.org/details/HumorOnl00'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_HumorOnl00',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 79,
    season: '1999',
    episodeOfSeason: 16,
    titles: ['New Age Websites', 'New Age Web Sites'],
    date: 932079600000,
    youtubeURL: 'https://www.youtube.com/watch?v=TClAYYCYgKw',
    internetArchiveURL: ['https://archive.org/details/nc439_new_age_websites'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc439_new_age_websites',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 80,
    season: '1999',
    episodeOfSeason: 17,
    titles: ['Personal Investing Online', 'Personal Investing Online'],
    date: 921024000000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 81,
    season: '1999',
    episodeOfSeason: 18,
    titles: ['Consumer Protection Online', 'Consumer Protection Online'],
    date: 928450800000,
    youtubeURL: 'https://www.youtube.com/watch?v=jr67d93mGxc',
    internetArchiveURL: ['https://archive.org/details/Consumer99'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Consumer99',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 82,
    season: '1999',
    episodeOfSeason: 19,
    titles: ['Online Collecting', 'Online Collecting'],
    date: 931474800000,
    youtubeURL: 'https://www.youtube.com/watch?v=oBnGSthRkw4',
    internetArchiveURL: ['https://archive.org/details/nc440_online_collecting'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc440_online_collecting',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 83,
    season: '1999',
    episodeOfSeason: 20,
    titles: ['Webby Awards 1999 - Part One', 'Webby Awards 1999 – Part One'],
    date: 925426800000,
    youtubeURL: 'https://www.youtube.com/watch?v=aC-HW8-E7Tg',
    internetArchiveURL: ['https://archive.org/details/WebbyAwa99'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_WebbyAwa99',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 84,
    season: '1999',
    episodeOfSeason: 21,
    titles: ['Webby Awards 1999 - Part Two', 'Webby Awards 1999 – Part Two'],
    date: 926031600000,
    youtubeURL: 'https://www.youtube.com/watch?v=idMd_5FUmqM',
    internetArchiveURL: ['https://archive.org/details/WebbyAwa99_2'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_WebbyAwa99_2',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 85,
    season: '2000',
    episodeOfSeason: 1,
    titles: ['Online Job Hunting', 'Online Job Hunting'],
    date: 953251200000,
    youtubeURL: 'https://www.youtube.com/watch?v=TzGL1rNm05Y',
    internetArchiveURL: ['https://archive.org/details/OnlineJo2000'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_OnlineJo2000',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 86,
    season: '2000',
    episodeOfSeason: 2,
    titles: ['Entertainment on the Web', 'Entertainment on the Web'],
    date: null,
    youtubeURL: 'https://www.youtube.com/watch?v=pJTJ1bbXQnM',
    internetArchiveURL: ['https://archive.org/details/Entertai2000'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Entertai2000',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 87,
    season: '2000',
    episodeOfSeason: 3,
    titles: ['Finding People Online', 'Finding People Online'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/FindingP2000'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_FindingP2000',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 88,
    season: '2000',
    episodeOfSeason: 4,
    titles: ['Net Games', 'Net Games'],
    date: null,
    youtubeURL:
      'https://www.youtube.com/watch?v=twK_6n_528w&pp=ygURbmV0Y2FmZSBuZXQgZ2FtZXM%3D',
    internetArchiveURL: ['https://archive.org/details/NetGames00'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_NetGames00',
    ],
    watched: true,
    streamTitle: 'FACE of WAR: Chaos Theory',
    streamDate: 1710460800000,
    streamURL: 'https://www.youtube.com/watch?v=TnZWb6DMPoE',
  },
  {
    index: 89,
    season: '2000',
    episodeOfSeason: 5,
    titles: [
      'Web Startups April 13th (2000)',
      'Net Cafe: Web StartUps – April 13, 2000',
    ],
    date: 955580400000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/NewWebBu01_4'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_NewWebBu01_4',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 90,
    season: '2000',
    episodeOfSeason: 6,
    titles: [
      'Web Startups April 14th',
      'Net Cafe: Web StartUps – April 14, 2000',
    ],
    date: 955666800000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/PreIPOCo00'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_PreIPOCo00',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 91,
    season: '2000',
    episodeOfSeason: 7,
    titles: ['Web Startups May 5th', 'Net Cafe: Web StartUps – May 5, 2000'],
    date: 957481200000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/NewWebEn2000'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_NewWebEn2000',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 92,
    season: '2000',
    episodeOfSeason: 8,
    titles: ['Web Startups May 26th', 'Net Cafe: Web StartUps – May 26, 2000'],
    date: 959295600000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/PreIPOCo01'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_PreIPOCo01',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 93,
    season: '2000',
    episodeOfSeason: 9,
    titles: ['Grim Reaper Web Sites (2000)', 'Grim Reaper Web Sites (2000)'],
    date: 964134000000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/GrimReap00'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_GrimReap00',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 94,
    season: '2000',
    episodeOfSeason: 10,
    titles: [
      'Web Startups November 3rd',
      'Net Cafe: Web StartUps – November 3, 2000',
    ],
    date: 973209600000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_529_newb'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_529_newb',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 95,
    season: '2000',
    episodeOfSeason: 11,
    titles: [
      'Web Startups December 7th (2000)',
      'Net Cafe: Web StartUps – Dec 7, 2000',
    ],
    date: 976147200000,
    youtubeURL: 'null',
    internetArchiveURL: ['https://archive.org/details/StateOfT02'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_StateOfT02',
    ],
    watched: true,
    streamTitle: 'FAT 32 QUICK BLAST - CHEIFEIT-M (A.M.)',
    streamDate: 1671494400000,
    streamURL: 'https://www.youtube.com/watch?v=p1dc-7pkXlk',
  },
  {
    index: 96,
    season: '2000',
    episodeOfSeason: 12,
    titles: ['Webby Awards 2000 Part One', 'Webby Awards 2000 – Part One'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/2000Webb00'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_2000Webb00',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 97,
    season: '2000',
    episodeOfSeason: 13,
    titles: ['Webby Awards 2000 Part Two', 'Webby Awards 2000 – Part Two'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/2000Webb00_2'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_2000Webb00_2',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 98,
    season: '2001',
    episodeOfSeason: 1,
    titles: ['Conspiracy Theories (2001)', 'Conspiracy Theories (2001)'],
    date: 980985600000,
    youtubeURL:
      'https://www.youtube.com/watch?v=CGjDPGWagc8&pp=ygUjbmV0IGNhZmUgQ29uc3BpcmFjeSBUaGVvcmllcyAoMjAwMSk%3D',
    internetArchiveURL: ['https://archive.org/details/Conspira2001'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Conspira2001',
    ],
    watched: true,
    streamTitle: 'Stream',
    streamDate: 1713826800000,
    streamURL: 'https://www.youtube.com/watch?v=gzZchH67HQo',
  },
  {
    index: 99,
    season: '2001',
    episodeOfSeason: 1,
    titles: ['Interesting Web Sites', 'Interesting Web Sites'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 100,
    season: '2001',
    episodeOfSeason: 2,
    titles: ['New Web Sites', 'New Web Sites – Part 1'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/NewWebSi2001'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_NewWebSi2001',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 101,
    season: '2001',
    episodeOfSeason: 3,
    titles: ['State of the Web', 'State of the Web (2001)'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/Stateoft2001'],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 102,
    season: '2001',
    episodeOfSeason: 4,
    titles: [
      'Web Startups March 9th',
      'Net Cafe: Web StartUps – March 9, 2001',
    ],
    date: 984096000000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_530_newb'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_530_newb',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 103,
    season: '2001',
    episodeOfSeason: 5,
    titles: [
      'Web Startups April 6th',
      'Net Cafe: Web StartUps – April 6, 2001',
    ],
    date: 986511600000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_533_neww'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_533_neww',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 104,
    season: '2001',
    episodeOfSeason: 6,
    titles: [
      'Web Startups April 13th (2001)',
      'Net Cafe: Web StartUps – April 13, 2001',
    ],
    date: 987116400000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_528_netc'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_528_netc',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 105,
    season: '2001',
    episodeOfSeason: 7,
    titles: [
      'Web Startups April 20th',
      'Net Cafe: Web StartUps – April 20, 2001',
    ],
    date: 987721200000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/HotNewWe01_7'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_HotNewWe01_7',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 106,
    season: '2001',
    episodeOfSeason: 8,
    titles: ['Web Startups May 4th', 'Net Cafe: Web StartUps – May 4, 2001'],
    date: 988930800000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/Internet01_2'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Internet01_2',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 107,
    season: '2001',
    episodeOfSeason: 9,
    titles: ['Web Startups May 11th', 'Net Cafe: Web StartUps – May 11, 2001'],
    date: 989535600000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/HotNewWe01_6'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_HotNewWe01_6',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 108,
    season: '2001',
    episodeOfSeason: 10,
    titles: ['Web Startups June 1st', 'Net Cafe: Web StartUps – June 1, 2001'],
    date: 991350000000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/HotNewWe01_3'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_HotNewWe01_3',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 109,
    season: '2001',
    episodeOfSeason: 11,
    titles: ['Web Startups June 8th', 'Net Cafe: Web StartUps – June 8, 2001'],
    date: 991954800000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/HotNewWe01_4'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_HotNewWe01_4',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 110,
    season: '2001',
    episodeOfSeason: 12,
    titles: [
      'Web Startups June 15th',
      'Net Cafe: Web StartUps – June 15, 2001',
    ],
    date: 992559600000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/NewWebBu01_2'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_NewWebBu01_2',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 111,
    season: '2001',
    episodeOfSeason: 13,
    titles: [
      'Web Startups June 29th',
      'Net Cafe: Web StartUps – June 29, 2001',
    ],
    date: 993769200000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/Internet2001'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_Internet2001',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 112,
    season: '2001',
    episodeOfSeason: 14,
    titles: ['Web Startups October 8th', 'Web Startups October 8th'],
    date: 1002495600000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 113,
    season: '2001',
    episodeOfSeason: 14,
    titles: ['Web Startups October 20th', 'Web Startups October 20th'],
    date: 1003532400000,
    youtubeURL: 'https://www.youtube.com/watch?v=1twivxrrxo0',
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 114,
    season: '2001',
    episodeOfSeason: 15,
    titles: [
      'Web Startups December 1st',
      'Net Cafe: Web StartUps – Dec 1, 2000',
    ],
    date: 1007164800000,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 115,
    season: '2001',
    episodeOfSeason: 16,
    titles: [
      'Web Startups December 7th (2001)',
      'Net Cafe: Web StartUps – Dec 7, 2001',
    ],
    date: 1007683200000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_616_netc'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_616_netc',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 116,
    season: '2001',
    episodeOfSeason: 17,
    titles: [
      'Web Startups December 14th',
      'Net Cafe: Web StartUps – Dec 14, 2001',
    ],
    date: 1008288000000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_617_netc'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_617_netc',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 117,
    season: '2002',
    episodeOfSeason: 1,
    titles: ['Home Improvement (2002)', 'Home Improvement'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 118,
    season: '2002',
    episodeOfSeason: 2,
    titles: ['Nicholas Negroponte Part One', 'Nicholas Negroponte – Part One'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [
      'https://archive.org/details/nc613_nicholas_negroponte_pt1',
    ],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc613_nicholas_negroponte_pt1',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 119,
    season: '2002',
    episodeOfSeason: 3,
    titles: ['Nicholas Negroponte Part Two', 'Nicholas Negroponte – Part Two'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: [
      'https://archive.org/details/nc615_nicholas_negroponte_pt2',
    ],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_nc615_nicholas_negroponte_pt2',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 120,
    season: '2002',
    episodeOfSeason: 4,
    titles: ['State of the Web', 'State of the Web Part Two'],
    date: null,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/Stateoft2002'],
    framesURL: [],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 121,
    season: '2002',
    episodeOfSeason: 5,
    titles: [
      'Web Startups January 4th',
      'Net Cafe: Web StartUps – Jan 4, 2002',
    ],
    date: 1010102400000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_609_netc'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_609_netc',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 122,
    season: '2002',
    episodeOfSeason: 6,
    titles: [
      'Web Startups January 11th',
      'Net Cafe: Web StartUps – Jan 11, 2002',
    ],
    date: 1010707200000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_610_netc'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_610_netc',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 123,
    season: '2002',
    episodeOfSeason: 7,
    titles: [
      'Web Startups February 15th',
      'Net Cafe: Web StartUps – Feb 15, 2002',
    ],
    date: 1014336000000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_611_netc'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_611_netc',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 124,
    season: '2002',
    episodeOfSeason: 8,
    titles: [
      'Web Startups February 22nd',
      'Net Cafe: Web StartUps – Feb 22, 2002',
    ],
    date: 1014336000000,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/tmp_nc_612_netc'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_tmp_nc_612_netc',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 125,
    season: '2002',
    episodeOfSeason: 9,
    titles: [
      'Group Therapy Net Style (2002)',
      'Group Therapy Net Style (2002)',
    ],
    date: null,
    youtubeURL: null,
    internetArchiveURL: ['https://archive.org/details/GroupThe02'],
    framesURL: [
      'https://api.gdeltproject.org/api/v2/tvv/tvv?id=IAITEM_GroupThe02',
    ],
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
];

module.exports = netcafeEpisodes;
