/*
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
    
    {
      index: 0,
      season: 1996,
      episodeOfSeason: 1,
      titles: [''],
      date: '1996',
    },
 
    {
      '1996': 10,
      '1997': 23,
      '1998': 30,
      '1999': 21,
      '2000': 11,
      '2001': 17,
      '2002': 7,
    }
*/

const netcafeEpisodes = [
  {
    index: 1,
    season: '1996',
    episodeOfSeason: 1,
    titles: ['Hackers'],
    date: 844210800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 2,
    season: '1996',
    episodeOfSeason: 2,
    titles: ["UFO's"],
    date: 844815600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 3,
    season: '1996',
    episodeOfSeason: 3,
    titles: ['Politics on the Web'],
    date: 845506800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 4,
    season: '1996',
    episodeOfSeason: 4,
    titles: ['Dark Side of the Net'],
    date: 845938800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 5,
    season: '1996',
    episodeOfSeason: 5,
    titles: ['Women on the Web'],
    date: 846460800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 6,
    season: '1996',
    episodeOfSeason: 6,
    titles: ['Games'],
    date: 847065600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 7,
    season: '1996',
    episodeOfSeason: 7,
    titles: ['The 3D Web'],
    date: 847843200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 8,
    season: '1996',
    episodeOfSeason: 8,
    titles: ['Music'],
    date: 848275200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 9,
    season: '1996',
    episodeOfSeason: 9,
    titles: ['Movies'],
    date: 849571200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 10,
    season: '1996',
    episodeOfSeason: 10,
    titles: ['Writers'],
    date: 850867200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 11,
    season: '1997',
    episodeOfSeason: 1,
    titles: ['Love and Romance on the Web'],
    date: 853459200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 12,
    season: '1997',
    episodeOfSeason: 2,
    titles: ['Art on the Net'],
    date: 854064000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 13,
    season: '1997',
    episodeOfSeason: 3,
    titles: ['Electronic Communities'],
    date: 854668800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 14,
    season: '1997',
    episodeOfSeason: 4,
    titles: ['Weird Science'],
    date: 855792000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 15,
    season: '1997',
    episodeOfSeason: 5,
    titles: ['Travel Sites Online'],
    date: 856483200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 16,
    season: '1997',
    episodeOfSeason: 6,
    titles: ['Equality and Diversity'],
    date: 857088000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 17,
    season: '1997',
    episodeOfSeason: 7,
    titles: ['Religion'],
    date: 858297600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 18,
    season: '1997',
    episodeOfSeason: 8,
    titles: ['Disinformation on the Web'],
    date: 858902400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 19,
    season: '1997',
    episodeOfSeason: 9,
    titles: ['Health Sites'],
    date: 859507200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 20,
    season: '1997',
    episodeOfSeason: 10,
    titles: ['TV Shows Online'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 21,
    season: '1997',
    episodeOfSeason: 11,
    titles: ['Censorship Online'],
    date: 826761600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 21,
    season: '1997',
    episodeOfSeason: 11.5,
    titles: ['Weird Web', 'The Weird Web'],
    date: 861922800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 22,
    season: '1997',
    episodeOfSeason: 12,
    titles: ['Online Sports'],
    date: 880675200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 23,
    season: '1997',
    episodeOfSeason: 13,
    titles: ['Privacy in Cyberspace'],
    date: 883094400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 24,
    season: '1997',
    episodeOfSeason: 14,
    titles: ['Science Fiction Online'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 25,
    season: '1997',
    episodeOfSeason: 15,
    titles: ['The Virtual Zoo'],
    date: 880070400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 26,
    season: '1997',
    episodeOfSeason: 17,
    titles: ['Virtual Doctors'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 27,
    season: '1997',
    episodeOfSeason: 18,
    titles: ['Web Radio'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 28,
    season: '1997',
    episodeOfSeason: 19,
    titles: ['Webby Awards 1997'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 29,
    season: '1997',
    episodeOfSeason: 20,
    titles: ['Comic Books on the Web'],
    date: 852854400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 30,
    season: '1997',
    episodeOfSeason: 21,
    titles: ['Online Sports'],
    date: 880675200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 31,
    season: '1997',
    episodeOfSeason: 22,
    titles: ['Privacy in Cyberspace'],
    date: 877647600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 32,
    season: '1997',
    episodeOfSeason: 23,
    titles: ['Web Radio'],
    date: 877042800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 33,
    season: '1997',
    episodeOfSeason: 24,
    titles: ['Comic Books'],
    date: 852854400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 34,
    season: '1998',
    episodeOfSeason: 1,
    titles: ['Voyeurism Online'],
    date: 885513600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 35,
    season: '1998',
    episodeOfSeason: 2,
    titles: ['War on the Web'],
    date: 887932800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 36,
    season: '1998',
    episodeOfSeason: 3,
    titles: ['Chat Rooms'],
    date: 907887600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 37,
    season: '1998',
    episodeOfSeason: 6,
    titles: ['Cyber Communities'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 38,
    season: '1998',
    episodeOfSeason: 7,
    titles: ['Cyber News'],
    date: 888883200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 39,
    season: '1998',
    episodeOfSeason: 8,
    titles: ['Cyber Sports'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 40,
    season: '1998',
    episodeOfSeason: 9,
    titles: ['Buy It Online'],
    date: 889747200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 41,
    season: '1998',
    episodeOfSeason: 10,
    titles: ['Gambling and Gaming on the Web'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 42,
    season: '1998',
    episodeOfSeason: 11,
    titles: ['Games on the Net'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 43,
    season: '1998',
    episodeOfSeason: 14,
    titles: ['Home Improvement'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 44,
    season: '1998',
    episodeOfSeason: 16,
    titles: ['Investing Online'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 45,
    season: '1998',
    episodeOfSeason: 19,
    titles: ['Online Activism'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 46,
    season: '1998',
    episodeOfSeason: 21,
    titles: ['Safe Kids Safe Net'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 47,
    season: '1998',
    episodeOfSeason: 23,
    titles: ['Small Business Resources on the Net'],
    date: 895791600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 48,
    season: '1998',
    episodeOfSeason: 24,
    titles: ['Space Science'],
    date: 893977200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 49,
    season: '1998',
    episodeOfSeason: 25,
    titles: ['The Global Net'],
    date: 910915200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 50,
    season: '1998',
    episodeOfSeason: 29,
    titles: ['TV Shows Online'],
    date: 878256000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 51,
    season: '1998',
    episodeOfSeason: 30,
    titles: ['Finding Anyone / Anything Online'],
    date: 886118400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 52,
    season: '1998',
    episodeOfSeason: 32,
    titles: ['Best SOHO Resources'],
    date: 895791600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 53,
    season: '1998',
    episodeOfSeason: 33,
    titles: ['Grim Reaper Web Sites'],
    date: 898815600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 54,
    season: '1998',
    episodeOfSeason: 34,
    titles: ['Humor on the Web'],
    date: 899420400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 55,
    season: '1998',
    episodeOfSeason: 35,
    titles: ['Group Therapy Net Style'],
    date: 900630000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 56,
    season: '1998',
    episodeOfSeason: 36,
    titles: ['Cyber Chat'],
    date: 901234800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 57,
    season: '1998',
    episodeOfSeason: 37,
    titles: ['Jobs and Careers'],
    date: 902444400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 58,
    season: '1998',
    episodeOfSeason: 38,
    titles: ['The Hollywood Connection'],
    date: 903049200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 59,
    season: '1998',
    episodeOfSeason: 39,
    titles: ['Sex Online'],
    date: 904863600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 60,
    season: '1998',
    episodeOfSeason: 40,
    titles: ['Cool Home Pages'],
    date: 906073200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 61,
    season: '1998',
    episodeOfSeason: 41,
    titles: ['Making Money On Line'],
    date: 906678000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 62,
    season: '1998',
    episodeOfSeason: 42,
    titles: ['Portals'],
    date: 911520000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 63,
    season: '1998',
    episodeOfSeason: 43,
    titles: ['Space Science'],
    date: 893977200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 64,
    season: '1999',
    episodeOfSeason: 1,
    titles: ['Incredibly Useful Sites'],
    date: 923612400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 65,
    season: '1999',
    episodeOfSeason: 2,
    titles: ['Online Literature'],
    date: 915753600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 66,
    season: '1999',
    episodeOfSeason: 3,
    titles: ['Adventure Travel Online'],
    date: 916963200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 67,
    season: '1999',
    episodeOfSeason: 4,
    titles: ['Crime and Justice'],
    date: 924822000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 68,
    season: '1999',
    episodeOfSeason: 5,
    titles: ['Performing Arts on the Web'],
    date: 929055600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 69,
    season: '1999',
    episodeOfSeason: 6,
    titles: ['Lions and Tigers and Bears'],
    date: 930265200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 70,
    season: '1999',
    episodeOfSeason: 7,
    titles: ['Hollywood on the Net'],
    date: 930870000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 71,
    season: '1999',
    episodeOfSeason: 8,
    titles: ['Investing Online'],
    date: 941760000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 72,
    season: '1999',
    episodeOfSeason: 9,
    titles: ['Lifelong Learning'],
    date: 938732400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 73,
    season: '1999',
    episodeOfSeason: 10,
    titles: ['Just for Fun', 'Fun Web Sites (1999)'],
    date: 939337200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 74,
    season: '1999',
    episodeOfSeason: 11,
    titles: ['E-Commerce'],
    date: 940546800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 75,
    season: '1999',
    episodeOfSeason: 12,
    titles: ['Conspiracy Theories'],
    date: 940546800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 76,
    season: '1999',
    episodeOfSeason: 13,
    titles: ['Cyber Kids'],
    date: 945129600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 77,
    season: '1999',
    episodeOfSeason: 14,
    titles: ['Xtreme Web', 'Extreme Web'],
    date: 945734400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 78,
    season: '1999',
    episodeOfSeason: 15,
    titles: ['Humor Online'],
    date: 946339200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 79,
    season: '1999',
    episodeOfSeason: 16,
    titles: ['New Age Websites'],
    date: 932079600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 80,
    season: '1999',
    episodeOfSeason: 17,
    titles: ['Personal Investing Online'],
    date: 921024000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 81,
    season: '1999',
    episodeOfSeason: 18,
    titles: ['Consumer Protection Online'],
    date: 928450800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 82,
    season: '1999',
    episodeOfSeason: 19,
    titles: ['Online Collecting'],
    date: 931474800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 83,
    season: '1999',
    episodeOfSeason: 20,
    titles: ['Webby Awards 1999 - Part One'],
    date: 925426800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 84,
    season: '1999',
    episodeOfSeason: 21,
    titles: ['Webby Awards 1999 - Part Two'],
    date: 926031600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 85,
    season: '2000',
    episodeOfSeason: 1,
    titles: ['Online Job Hunting'],
    date: 953251200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 86,
    season: '2000',
    episodeOfSeason: 2,
    titles: ['Entertainment on the Web'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 87,
    season: '2000',
    episodeOfSeason: 3,
    titles: ['Finding People Online'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 88,
    season: '2000',
    episodeOfSeason: 4,
    titles: ['Net Games'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 89,
    season: '2000',
    episodeOfSeason: 5,
    titles: ['Web Startups April 13th'],
    date: 955580400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 90,
    season: '2000',
    episodeOfSeason: 6,
    titles: ['Web Startups May 5th'],
    date: 957481200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 91,
    season: '2000',
    episodeOfSeason: 7,
    titles: ['Web Startups May 26th'],
    date: 959295600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 92,
    season: '2000',
    episodeOfSeason: 8,
    titles: ['Web Startups November 3rd'],
    date: 973209600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 93,
    season: '2000',
    episodeOfSeason: 9,
    titles: ['Web Startups December 7th'],
    date: 976147200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: 'partial',
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 94,
    season: '2000',
    episodeOfSeason: 10,
    titles: ['Webby Awards 2000 Part One'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 95,
    season: '2000',
    episodeOfSeason: 11,
    titles: ['Webby Awards 2000 Part Two'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 96,
    season: '2001',
    episodeOfSeason: 1,
    titles: ['Conspiracy Theories', 'Conspiracy Theories (2001)'],
    date: 980985600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 97,
    season: '2001',
    episodeOfSeason: 1,
    titles: ['Interesting Web Sites'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 98,
    season: '2001',
    episodeOfSeason: 2,
    titles: ['New Web Sites'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 99,
    season: '2001',
    episodeOfSeason: 3,
    titles: ['State of the Web'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 100,
    season: '2001',
    episodeOfSeason: 4,
    titles: ['Web Startups March 9th'],
    date: 984096000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 101,
    season: '2001',
    episodeOfSeason: 5,
    titles: ['Web Startups April 6th'],
    date: 986511600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 102,
    season: '2001',
    episodeOfSeason: 6,
    titles: ['Web Startups April 13th'],
    date: 987116400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 103,
    season: '2001',
    episodeOfSeason: 7,
    titles: ['Web Startups April 20th'],
    date: 987721200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 104,
    season: '2001',
    episodeOfSeason: 8,
    titles: ['Web Startups May 4th'],
    date: 988930800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 105,
    season: '2001',
    episodeOfSeason: 9,
    titles: ['Web Startups May 11th'],
    date: 989535600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 106,
    season: '2001',
    episodeOfSeason: 10,
    titles: ['Web Startups June 1st'],
    date: 991350000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 107,
    season: '2001',
    episodeOfSeason: 11,
    titles: ['Web Startups June 8th'],
    date: 991954800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 108,
    season: '2001',
    episodeOfSeason: 12,
    titles: ['Web Startups June 15th'],
    date: 992559600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 109,
    season: '2001',
    episodeOfSeason: 13,
    titles: ['Web Startups June 29th'],
    date: 993769200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 110,
    season: '2001',
    episodeOfSeason: 14,
    titles: ['Web Startups October 8th'],
    date: 1002495600000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 111,
    season: '2001',
    episodeOfSeason: 15,
    titles: ['Web Startups December 1st'],
    date: 1007164800000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 112,
    season: '2001',
    episodeOfSeason: 16,
    titles: ['Web Startups December 7th'],
    date: 1007683200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 113,
    season: '2001',
    episodeOfSeason: 17,
    titles: ['Web Startups December 14th'],
    date: 1008288000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 114,
    season: '2002',
    episodeOfSeason: 1,
    titles: ['Home Improvement'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 115,
    season: '2002',
    episodeOfSeason: 2,
    titles: ['Nicholas Negroponte Part One'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 116,
    season: '2002',
    episodeOfSeason: 3,
    titles: ['Nicholas Negroponte Part Two'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 117,
    season: '2002',
    episodeOfSeason: 4,
    titles: ['State of the Web'],
    date: null,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 118,
    season: '2002',
    episodeOfSeason: 5,
    titles: ['Web Startups January 4th'],
    date: 1010102400000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 119,
    season: '2002',
    episodeOfSeason: 6,
    titles: ['Web Startups January 11th'],
    date: 1010707200000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 120,
    season: '2002',
    episodeOfSeason: 7,
    titles: ['Web Startups February 22nd'],
    date: 1014336000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: false,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
  {
    index: 143,
    season: '2002',
    episodeOfSeason: 8,
    titles: ['Cyber Dating'],
    date: 1028070000000,
    internetArchiveURL: null,
    youtubeURL: null,
    framesURL: null,
    watched: true,
    streamTitle: null,
    streamDate: null,
    streamURL: null,
  },
];

module.exports = netcafeEpisodes;
